language: java
jdk:
- oraclejdk8
addons:
  apt:
    packages:
    - graphviz
  sonarcloud:
    organization: "coolstuffsoftware-github"
    branches:
    - master
    - develop
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
