language: java
jdk:
- oraclejdk8
addons:
  apt:
    packages:
    - graphviz
  sonarcloud:
    organization: "coolstuffsoftware-github"
    branches:
    - master
    - develop
script:
  - sonar-scanner
